name: Maven CI/CD Pipeline

# Quando este pipeline ser치 executado
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Jobs do pipeline
jobs:
  build:
    runs-on: ubuntu-latest

    # Passos que o job ir치 executar
    steps:
    - name: Checkout c칩digo-fonte
      uses: actions/checkout@v2

    - name: Configurar JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build com Maven
      run: mvn clean install -DskipTests

    - name: Rodar Testes
      run: mvn test

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout c칩digo-fonte
      uses: actions/checkout@v2

    - name: Configurar JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build Docker Image
      run: docker build -t meuapp:latest .

    - name: Testar Docker Image
      run: docker run --rm meuapp:latest

